"use strict";

exports.operations = Object.freeze({
	ADD: 0x0,
	UPDATE: 0x1,
	REPLY: 0x2,
	DELETE: 0x3,
	ADD_AND_REFER: 0x4,
	UPDATE_AND_REFER: 0x5,
	ENDORSE: 0x6,
	REMOVE_ENDORSEMENT: 0x7,
	DISAPPROVE: 0x8,
	REMOVE_DISAPPROVAL: 0x09,
	ENDORSE_AND_REPLY: 0xA,
	DISAPPROVE_AND_REPLY: 0xB,
	CLOSE_ACCOUNT: 0xFD,
	RAW: 0xFF
});
